plugins {
    id 'java'
    id("org.beryx.jlink") version "4.1.1"
    id("org.openjfx.javafxplugin") version "0.1.0"
}

group = 'com.derpderp'
version = '0.0.1'

repositories {
    mavenCentral()
}

javafx {
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

application {
    mainClass = "com.derpderphurr.duku.Main"
    mainModule = "duku"
}


dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}